apiVersion: apps/v1
kind: StatefulSet
metadata:
  # This name uniquely identifies the StatefulSet
  name: minio
spec:
  serviceName: minio
  podManagementPolicy: Parallel
  replicas: {{ .Params.NODE_COUNT }}
  selector:
    matchLabels:
      app: minio # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: minio # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: minio
        env:
        - name: MINIO_ACCESS_KEY
          value: "minio"
        - name: MINIO_SECRET_KEY
          value: "minio123"
        image: {{ .Params.NODE_DOCKER_IMAGE }}
        args:
        - server
        - http://minio-{0...{{ .Params.NODE_COUNT }}}.minio.default.svc.cluster.local/data
        ports:
        - containerPort: {{ .Params.MINIO_CONTAINER_PORT }}
        # These volume mounts are persistent. Each pod in the PetSet
        # gets a volume mounted based on this field.
        volumeMounts:
        - name: data
          mountPath: {{ .Params.MINIO_MOUNT_PATH }}
        # Liveness probe detects situations where MinIO server instance
        # is not working properly and needs restart. Kubernetes automatically
        # restarts the pods if liveness checks fail.
        livenessProbe:
          httpGet:
            path: {{ .Params.MINIO_LIVENESS_PROBE_PATH }}
            port: {{ .Params.MINIO_CONTAINER_PORT }}
          initialDelaySeconds: {{ .Params.MINIO_LIVENESS_PROBE_INITIAL_DELAY_SECONDS }}
          periodSeconds: {{ .Params.MINIO_LIVENESS_PROBE_PERIOD_SECONDS }}
        # Readiness probe detects situations where MinIO server instance
        # is not ready to accept connections. Kubernetes automatically
        # stops all the traffic to the pods if readiness checks fail.
        readinessProbe:
          httpGet:
            path: {{ .Params.MINIO_READYNESS_PROBE_PATH }}
            port: {{ .Params.MINIO_CONTAINER_PORT }}
          initialDelaySeconds: {{ .Params.MINIO_READYNESS_PROBE_INITIAL_DELAY_SECONDS }}
          periodSeconds: {{ .Params.MINIO_READYNESS_PROBE_PERIOD_SECONDS }}
  # These are converted to volume claims by the controller
  # and mounted at the paths mentioned above.
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
